
cc_test(
    name = "state",
    srcs = ["state_test.cc"],
    size = "medium",
    timeout = "moderate",
    deps = [
      "//automaton/core/crypto",
      "//automaton/core/crypto/cryptopp",
      "//automaton/core/state",
      "@gtest//:gtest_main",
    ],
)
