# Automaton examples - easylogging++

package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "demo_easyloggingpp",
  srcs = [
    "demo_easyloggingpp.cc",
  ],
  deps = [
    "@easyloggingpp//:easyloggingpp",
  ],
)
