cc_binary (
	name = "tcp_impl_test",
	srcs = ["tcp_impl_test.cc",],
	deps = [
    "//automaton/core/io",
    "//automaton/core/network:network_tcp",
  ],
)

cc_binary (
	name = "simulation_test",
	srcs = ["simulation_test.cc",],
	deps = [
    "//automaton/core/io",
    "//automaton/core/network:simulated_connection",
  ],
)
