# Automaton examples - crypto library

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "demo_crypto",
    srcs = [
      "miner_demo.cc",
      "basic_hash_miner.cc",
      "basic_hash_miner.h",
    ],
    deps = [
      "//crypto",
    ],
)
