# Automaton data schema & serialization implementation using google::protobuf

package(default_visibility = ["//visibility:public"])

cc_library(
	name = "protobuf",
  srcs = [
    "protobuf_schema.cc",
	  "protobuf_schema.h",
    "protobuf_schema_definition.cc",
    "protobuf_schema_definition.h",
    "protobuf_schema_message.cc",
    "protobuf_schema_message.h",
  ],
  deps = [
    "//data",
  ],
)
