# Automaton state library

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "state",
    srcs = [
      "state.cc",
      "state.h"
    ],
    hdrs = [
      "state.h",
    ],
)
