# Automaton state library

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "state",
    srcs = [
      "dummy_state.cc",
      "dummy_state.h",
      "state.cc",
      "state.h",
    ],
    hdrs = [
      "dummy_state.h",
      "state.h",
    ],
    deps = [
      "//crypto",
      "@com_github_glog_glog//:glog",
    ],
)
