# Automaton storage library

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "storage",
    srcs = [
      "blob_storage.cc",
      "blob_storage.h",
    ],
    hdrs = [
      "blob_storage.h",
    ],
)
