# Automaton storage library

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "storage",
    srcs = [
      "blobk_storage.cc",
      "blobk_storage.h",
    ],
    hdrs = [
      "blobk_storage.h",
    ],
)
