
cc_library(
  name = "scriptable",
  srcs = [
    "scriptable.cc",
    "scriptable.h",
    "scriptable_engine.cc",
    "scriptable_engine.h",
  ],
  hdrs = [
    "scriptable.h",
    "scriptable_engine.h",
  ],
  deps = [
    "//schema",
  ]
)
