# Automaton core node

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "node",
  srcs = [
	  "node.cc",
  ],
  hdrs = [
	  "node.h",
  ],
  deps = [
	  "//network:network_tcp",
    "//data:data_google_protobufs",
  ],
)
