# Automaton scripting library

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "script",
  srcs = [
  ],
  hdrs = [
  ],
  deps = [
    "//data",
    # "@boost//:asio",
  ],
)
