# Automaton scripting library

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "script",
  srcs = [
    "registry.cc",
  ],
  hdrs = [
    "registry.h",
  ],
  deps = [
    "//data",
    "//log",
    "@boost//:type_traits",
    "@boost//:config",
  ],
)
