#cc_test(
#  name = "selene_test",
#  srcs = glob([
#    "*.cc",
#    "*.h",
#  ]),
#  size = "small",
#  data = glob(["*.lua"]),
#  deps = [
#      "@lua//:liblua",
#      "@selene//:selene",
#  ]
#)
