# Automaton I/O utility library

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "io",
  srcs = [
    "io.cc",
  ],
  hdrs = [
    "io.h",
  ],
)

cc_library(
  name = "module",
  srcs = ["module.cc"],
  hdrs = ["module.h"],
  deps = [
    "//automaton/core/script",
  ],
)
