# Automaton crypto module interface

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "crypto",
  srcs = [
    "hash_transformation.cc",
    "hash_transformation.h",
    "digital_signature.cc",
    "digital_signature.h",
    "secure_random.cc",
    "secure_random.h",
  ],
  hdrs = [
    "hash_transformation.h",
    "digital_signature.h",
    "secure_random.h",
  ],
)
