# Automaton scripting library tests

package(default_visibility = ["//visibility:public"])

cc_test(
  name = "test_script",
  srcs = ["test_script.cc",],
  deps = [
    "//script",
    "//crypto:module",
    "//data:module",
    "//network:module",
    "//state:module",
    "@gtest//:gtest_main",
  ],
)
