cc_library(
  name = "automaton_core_net",
  srcs = [
	  "acceptor.cpp",
	  "connection.cpp",		
  ],
  hdrs = [
	  "acceptor.h",
	  "connection.h",
  ],
  deps = [
	  "@com_github_boost_asio//:asio",
  ],
)		
